site_name: HHaven Documentation
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
      primary: red
      accent: deep orange 
    - scheme: slate 
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode    
      primary: red
      accent: deep orange
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/jokelbaf/hhaven
repo_name: JokelBaf/hhaven

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jokelbaf
    - icon: fontawesome/brands/telegram
      link: https://t.me/jokelbaf
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/491588676074078218

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/jokelbaf"  target="_blank" rel="noopener">JokelBaf</a>